name: rust
on: [push]
jobs:
  fmt_clippy_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year:
          - 15
          - 16
          - 17
          - 21

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - run: cd ${{ matrix.year }} && cargo fmt --all -- --check
      - run: > 
          cd ${{ matrix.year }} &&
          cargo clippy --all
          --
          -D warnings
          -W clippy::shadow_reuse
          -W clippy::shadow_same
          -W clippy::shadow_unrelated
      - run: cd ${{ matrix.year }} && cargo test
