[package]
name = "day04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_deref = "1.1.1"
itertools = "*"
lazy_static = "1.4.0"
regex = "1.5.6"
utils = { path = "../../utils" }
